name: Terraform IaC

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  provision:
    runs-on: ubuntu-latest
    env:
      TF_VAR_project_id: "${{ secrets.GCP_PROJECT_ID }}"
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}'

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init
          
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve